// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpkKh6Vy671zzZeA1FsYc1cdPKlf0REyo',
    appId: '1:592779154326:web:6191e5b122e2abc1e043b7',
    messagingSenderId: '592779154326',
    projectId: 'spotify-68f75',
    authDomain: 'spotify-68f75.firebaseapp.com',
    storageBucket: 'spotify-68f75.appspot.com',
    measurementId: 'G-HLKTRN0ZWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfbjBlNRq3KokTkS_OTZnFtdd4gT0io20',
    appId: '1:592779154326:android:3a02e6acd35a9101e043b7',
    messagingSenderId: '592779154326',
    projectId: 'spotify-68f75',
    storageBucket: 'spotify-68f75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByOQNBO5X2TL9W8-xtljajFAlEKWOV6Hk',
    appId: '1:592779154326:ios:69ad61d160385269e043b7',
    messagingSenderId: '592779154326',
    projectId: 'spotify-68f75',
    storageBucket: 'spotify-68f75.appspot.com',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByOQNBO5X2TL9W8-xtljajFAlEKWOV6Hk',
    appId: '1:592779154326:ios:c93f256d7884ac67e043b7',
    messagingSenderId: '592779154326',
    projectId: 'spotify-68f75',
    storageBucket: 'spotify-68f75.appspot.com',
    iosBundleId: 'com.example.spotify.RunnerTests',
  );
}
